conflict in versions of jboss-logging
A java.lang.NoSuchMethodError: org.jboss.logging.Logger.debugf(Ljava/lang/String;I)V was thrown; which prevented the download.
With jersey.version 2.21 org.jboss.logging classes are packed directly in bean-validator-2.4.0-b31.jar with 2.25.1 the dependencies are different so the older jboss-logging can be excluded.